VIA_ENABLE = yes
VIAL_ENABLE = yes
QMK_SETTINGS = no

LTO_ENABLE = yes

VIALRGB_ENABLE = yes
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = WS2812

TAP_DANCE_ENABLE = no
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no